version: '3.8'

services:
  acha-api:
    image: ${DOCKER_USERNAME}/acha-api:latest
    container_name: acha-api
    ports:
      - "9090:9090"
    depends_on:
      - mysql
    networks:
      - acha-network

  mysql:
    image: mysql:8.0
    container_name: acha-mysql
    restart: always
    ports:
      - "9306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE_NAME}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_USER_PASSWORD}
    volumes:
      - acha-data:/var/lib/mysql
    networks:
      - acha-network

  redis:
    image: redis:latest
    container_name: acha-redis
    restart: always
    command: redis-server
    ports:
      - "9379:6379"
    networks:
      - aics-network

networks:
  acha-network:
    driver: bridge

volumes:
  acha-data: