version: '3.8'

services:
  acha-api:
    image: ${DOCKER_USERNAME}/acha-api:latest
    container_name: acha-api
    ports:
      - "9090:9090"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - mysql
    networks:
      - acha-network

  mysql:
    image: mysql:8.0
    container_name: acha-mysql
    restart: always
    ports:
      - "9306:3306"
    env_file:
      - .env
    volumes:
      - acha-data:/var/lib/mysql
    networks:
      - acha-network

  redis:
    image: redis:latest
    container_name: acha-redis
    restart: always
    command: redis-server
    env_file:
      - .env
    ports:
      - "9379:6379"
    networks:
      - acha-network

networks:
  acha-network:
    driver: bridge

volumes:
  acha-data: