version: '3.8'

services:
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - acha-network

  acha-api:
    image: ${DOCKER_USERNAME}/acha-api:latest
    container_name: acha-api
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - mysql
    volumes:
      - /home/ubuntu/service-account.json:/home/ubuntu/service-account.json
    networks:
      - acha-network

  mysql:
    image: mysql:8.0
    container_name: acha-mysql
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - acha-data:/var/lib/mysql
    networks:
      - acha-network

  redis:
    image: redis:latest
    container_name: acha-redis
    restart: always
    command: redis-server
    env_file:
      - .env
    ports:
      - "6379:6379"
    networks:
      - acha-network

networks:
  acha-network:
    driver: bridge

volumes:
  acha-data: